### ISSUE TITLE
ASR 결과값이 원치 않은게 나옵니다.

### ISSUE THREAD

**Issue by kaizen95** [hyung8758/Korean_ASR#2]
안녕하세요 올려주신 코드를 활용해서 음성인식을 만들어보고 있습니다. 

Kaldi_tutorial 까지는 성공했고, 이제 제 음성을 넣어서 디코딩하는 걸 시도해보고 있습니다만, 
일단 Kaldi_tutorial에 넣은 음성은 예제로 주신 음성과 달리 제가 직접 녹음한 명령어 위주로 넣어보았습니다.

예를 들면 요즘 시중에 있는 기가지니 또는 클로버처럼, 명령어에만 반응하는 식을 원해서, 그 명령어를 녹음한 걸 넣어봤는데..
문제는 그 명령어가 들어가지 않은 test01.wav 인데도 명령어로 결과값을 도출해버리는 문제가 발생합니다.

이걸 어떻게 하면 좋을지 한번 티켓을 올려봅니다. 

읽어주셔서 감사합니다.

(Tri1 Model, diy 로 테스트 해보았습니다.  사용하는 기기가 라즈베리 파이라서 그런건지 Tri3 이상으로는 안되더군요.)

**Comment by hyung8758** [comment]
답변이 많이 늦었지만 우선 달아봅니다.
lexicon에 원하는 단어만 추가하셨을경우, 그 단어들만 나오게 됩니다.
예를들어 lexicon에 "컴퓨터, 티비, 라디오"만 넣으셨을 경우, "라이터"을 발화하더라도 그와 가장 유사한 "라디오"만 나옵니다.
기본적인 대부분의 단어를 인식하면서 특정 명령어만 추가적으로 나오길 원한다면 기존 단어들의 lexicon은 유지하면서 추가 명령어를 덧붙여주셔야합니다. 
물론 언어모델의 lm.arpa에도 lexicon 모든 단어들이 포함된 훈련이 진행되어야합니다.
